import React,{useState} from 'react';
import {PageShell} from '../components/ui/PageShell';

export function ReferralsPage(){return <PageShell eyebrow="ACCOUNT / REFERRALS" title="Referrals" description="Invite friends and earn a percentage from eligible referral activity." action={<button className="primary">Share invite</button>}><div className="referral-card"><div><span className="eyebrow">INVITE FRIENDS</span><strong>Get 10% of your friends' earnings!</strong><p>Share your personal referral link with friends.</p><div className="ref-link"><span>https://gainiren.com/r/massi</span><button className="secondary">Copy</button></div></div><div className="ref-stats"><span><b>12</b>Total Referrals</span><span><b>1,250</b>Total Earned</span></div><div className="ref-levels"><h3>Referral Rewards</h3><div><span>🥇 Level 1 (10%)</span><b>+250</b></div><div><span>🥈 Level 2 (5%)</span><b>+120</b></div><div><span>🥉 Level 3 (3%)</span><b>+80</b></div></div></div></PageShell>}

export function ProfilePage(){const [dark,setDark]=useState(true);return <PageShell eyebrow="ACCOUNT / PROFILE" title="Profile" description="Manage your profile, preferences and security settings."><div className="profile-card"><div className="big-avatar">M</div><div><h2>Member</h2><p>Level 3 <span className="progress"><i/></span></p></div><div className="profile-balance"><span>🪙 2,480</span><small>Balance</small><span>♛ 12,680</span><small>Lifetime</small></div></div><div className="settings-list"><button><b>♙ Edit Profile</b><span>Update your member details</span><i>›</i></button><button><b>♢ Notifications</b><span>Manage alerts and updates</span><i className="toggle on">●</i></button><button><b>文 Language</b><span>English</span><i>›</i></button><button onClick={()=>setDark(!dark)}><b>◐ Dark Mode</b><span>{dark?'Enabled':'Disabled'}</span><i className="toggle on">●</i></button><button><b>⌁ Privacy & Security</b><span>Account protection</span><i>›</i></button></div></PageShell>}

const faqs=['How to earn coins?','When will I get my rewards?','How to withdraw money?','Why is my offer pending?'];
export function HelpPage(){return <PageShell eyebrow="SUPPORT / HELP" title="Help Center" description="Find quick answers and contact support when you need help."><div className="help-search">⌕ <span>Search for help...</span></div><div className="faq-list"><h3>Frequently Asked Questions</h3>{faqs.map(q=><button key={q}>{q}<span>›</span></button>)}</div><div className="contact-card"><h3>Contact Us</h3><div>✉ <span>support@gainiren.com</span></div><button className="primary small">● Live Chat</button></div></PageShell>}

export function AssistantPage(){const [text,setText]=useState('');return <PageShell eyebrow="SUPPORT / GAINIREN AI" title="GainiRen AI" description="Your AI reward assistant. Ask anything about earning and the platform."><div className="chat"><div className="ai-head"><span className="ai-orb">✦</span><div><b>GainiRen AI</b><small>Online • ready to help</small></div></div><div className="bubble ai">Hello, Massi! 👋<br/>I'm your AI assistant. Ask me anything!</div><div className="chat-suggestions"><button>How can I earn more coins?</button><button>Best offers right now?</button><button>Tips to get more rewards</button></div><div className="chat-input"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Type a message..."/><button className="primary" onClick={()=>setText('')}>↗</button></div></div></PageShell>}
