import React from 'react';
import {PageShell} from '../components/ui/PageShell';

export function ReferralsPage(){return <PageShell eyebrow="ACCOUNT / REFERRALS" title="Invite & earn together" description="Share your referral code and track eligible activity." action={<button className="primary">Share invite</button>}><div className="referral-card"><div><small>Your referral code</small><strong>GAINIREN123</strong><p>Presentation value only until your existing database is connected.</p></div><button className="secondary">Copy code</button><div className="ref-stats"><span><b>—</b>Invited</span><span><b>—</b>Active</span><span><b>—</b>Points earned</span></div></div></PageShell>}

export function ProfilePage(){return <PageShell eyebrow="ACCOUNT / PROFILE" title="Your profile" description="Manage your member details and account preferences." action={<button className="secondary">Security</button>}><div className="profile-card"><div className="big-avatar">A</div><div><h2>Member</h2><p>Profile data will be loaded from the existing database.</p></div><button className="secondary">Edit profile</button></div><div className="settings-list"><div><b>Email preferences</b><span>Manage notifications and updates</span><button className="toggle on">●</button></div><div><b>Security</b><span>Password, sessions and sign-in</span><button className="secondary">Manage</button></div><div><b>Privacy</b><span>Control how your account information is used</span><button className="secondary">Review</button></div></div></PageShell>}

export function HelpPage(){return <PageShell eyebrow="SUPPORT / HELP" title="Help Center" description="Find answers about earning, rewards and your account."><div className="resource-grid"><article className="resource-card"><div className="resource-brand">?</div><div><span className="tag">Getting started</span><h3>How GainiRen works</h3><p>Learn how offers, points and redemptions fit together.</p></div></article><article className="resource-card"><div className="resource-brand">↗</div><div><span className="tag">Rewards</span><h3>Withdrawal guide</h3><p>Understand eligibility, processing and supported methods.</p></div></article></div></PageShell>}

export function AssistantPage(){return <PageShell eyebrow="SUPPORT / GAINIREN AI" title="GainiRen AI" description="A guided assistant for the member experience."><div className="chat"><div className="bubble ai">Hi 👋 I can help explain the GainiRen interface and reward flow.</div><div className="bubble user">How can I earn more points?</div><div className="bubble ai">Explore the highest-value eligible offers and complete them according to each provider's rules.</div><div className="chat-input"><input placeholder="Ask GainiRen AI..."/><button className="primary">Send</button></div></div></PageShell>}
