import React from 'react';
import {navGroups} from '../data/mock';
import {useMember} from '../app/MemberContext';

export function Logo(){return <div className="brand"><span className="brand-mark">G</span><span>GainiRen</span></div>}
export function Icon({children}){return <span className="icon" aria-hidden="true">{children}</span>}
export function Sidebar({page,setPage}){const {member}=useMember();const name=member?.profile?.name||member?.profile?.full_name||member?.profile?.username||'Member';return <aside className="sidebar"><Logo/><div className="nav-groups">{navGroups.map(g=><div className="nav-group" key={g.label}><div className="nav-label">{g.label}</div>{g.items.map(([id,label,icon])=><button aria-current={page===id?'page':undefined} key={id} className={'nav-item '+(page===id?'active':'')} onClick={()=>setPage(id)}><Icon>{icon}</Icon><span>{label}</span>{id==='offers'&&<small className="nav-badge">NEW</small>}</button>)}</div>)}</div><div className="sidebar-help"><span>✦</span><div><b>Need help?</b><small>Visit the Help Center</small></div></div><div className="sidebar-user"><div className="avatar">{name.slice(0,1).toUpperCase()}</div><div><b>{name}</b><small>Member account</small></div><span className="online"/></div></aside>}
export function Topbar({page}){const {member}=useMember();const name=member?.profile?.name||member?.profile?.full_name||member?.profile?.username||'Member';return <header className="topbar"><div className="mobile-logo"><Logo/></div><div className="crumb"><span>GainiRen</span><i>/</i><b>{page.replace(/(^|_)(\w)/g,(_,a,b)=>b.toUpperCase())}</b></div><div className="top-actions"><button className="search" aria-label="Search"><span className="search-icon">⌕</span><span>Search anything</span><kbd>⌘ K</kbd></button><button className="round notification" aria-label="Notifications">♧<span className="notification-dot"/></button><button className="top-avatar" aria-label="Profile" onClick={()=>location.hash='profile'}>{name.slice(0,1).toUpperCase()}</button></div></header>}
export function MobileNav({page,setPage}){const items=[['dashboard','⌂','Home'],['offers','✦','Offers'],['tasks','◈','Earn'],['store','◆','Store'],['profile','●','Profile']];return <nav className="mobile-nav" aria-label="Mobile navigation">{items.map(([id,icon,label])=><button aria-current={page===id?'page':undefined} className={page===id?'active':''} key={id} onClick={()=>setPage(id)}><Icon>{icon}</Icon><span>{label}</span></button>)}</nav>}
